@host = http://localhost

@port = 3000

@url = {{host}}:{{port}}

### GET records from table
GET {{url}}/termek
Content-Type: application/json


### GET one record by ID

GET {{url}}/termek/4
Content-Type: application/json

### POST new record

POST {{url}}/termek
Content-Type: application/json

{
 "termek": "Boci Csoki",
 "kategoriaNev": "Desszertek",
 "nettoAr": 515,
 "egyseg": "db"
}

### DELETE user

DELETE  {{url}}/termek/4
Content-Type: application/json

### UPDATE user by id
PATCH {{url}}/termek/5
Content-Type: application/json

{
    "termek": "Boci csoki",
    "kategoriaNev": "Desszertek",
    "nettoAr": 500,
    "egyseg": "db"
}

### LOGIN

POST {{url}}/users/login
Content-Type: application/json

{
    "email": "Béla@teszt.hu",
    "password": "jelszo123"
}

### REGISTER

POST {{url}}/users/registration
Content-Type: application/json

{
    "name": "Béla",
    "email": "Béla@teszt.hu",
    "password": "jelszo123",
    "confirm": "jelszo123"
}

### UNIVWRSGAL

GET  {{url}}/users/role/like/admin
Content-Type: application/json

### EMAIL

POST {{url}}/sendmail
Content-Type: application/json

{
    "template": "registration",
    "to": "czakocsongor@turr.hu",
    "subject": "Hálókapitány",
    "data":{"username": "Sanyi",
    "email": "sanyi@gmail.com",
    "password":"Sanyi123.",
    "url": "http://localhost:4200"}
}